### ISSUE TITLE
This implementation is not streaming

### ISSUE THREAD

**Issue by X-Ryl669** [mattkrick/event-source-polyfill#2]
This implementation is the most elegant polyfill I've found. 

However, unless I'm missing something, this implementation is using XMLHttpRequest in IE/Edge and those are not calling the received callback until the answer is completely received, which kind of defeat the whole purpose of a streaming connection.
Typically, this means that IE/Edge will connect, close the connection or timeout, and then reconnect and so on. This is far from perfect from my point of view, since it's not better than simple ajax polling/long polling.

Am I missing something ?

**Comment by mattkrick** [comment]
the magic is in the header :wink: https://github.com/mattkrick/event-source-polyfill/blob/master/src/EventSourcePolyfill.ts#L65
make sure your server is configured correctly to handle it.
And your reverse proxy: https://github.com/ParabolInc/action/blob/master/src/server/sse/SSEConnectionHandler.js#L27

Check out the spec (link in the readme) to learn more. It's written remarkably well. SSE isn't magic, it's essentially just a long poll with a standardized way to handle reconnects.

**Comment by X-Ryl669** [comment]
Nope, we're not speaking about the same thing.
Try this simple test: let a long timeout (60s) just after line 63 ( `xhr.open`) so the client does not disconnect after few seconds. Then in the server, send an event every second.
You'll see that `xhr.onreadystatechange` won't be called after each second (on Edge) as it is in a true `EventSource` progress event, but only after all event are sent (that is after 60s or so). Edge does not provide progress callback in `XMLHttpRequest`, only in `XDomainRequest`, IIRC.

**Comment by mattkrick** [comment]
if you can get a repro test case up that'd be helpful, this is working for me in production. if a client is disconnecting after a few seconds then it's usually because their firewall or your reverse proxy is terminating long lived connections.

domain request was deprecated a looong time ago:
https://developer.mozilla.org/en-US/docs/Web/API/XDomainRequest
